Solution
mate-academy/react_keyboard pull request #186
Opened 2022-09-12 09:27 UTC by vladgusakovskiy

[DEMO LINK](https://vladgusakovskiy.github.io/react_keyboard/)

2022-09-12 09:58 UTC, roma-shafihullin approved these changes
good solution 👍

2022-09-12 10:33 UTC, denys-danyliuk requested changes
GJ
let's use event.code to check if the pressed key is space and write [spac
<img width="202" alt="Знімок екрана 2022-09-12 о 13 18 30" src="https://user-images.githubusercontent.com/106310796/189632758-1793e158-5c8c-4905-b335-67d8d779bca2.png">
e] if so

2022-09-14 07:13 UTC, denys-danyliuk requested changes

2022-09-14 07:13 UTC, denys-danyliuk commented on src/App.tsx
> +      this.setState({ pressedKey: `The last pressed key is [${event.key}]` });
don't save a whole string to pressedKey, save only a name of the key

2022-09-14 13:08 UTC, denys-danyliuk approved these changes
Good job, you probably forgot to do deploy, because when I press space I see empty space

2022-09-14 13:08 UTC, denys-danyliuk commented on src/App.tsx
> +  render(): React.ReactNode {
```suggestion
  render() {
```

2024-01-15 19:58 UTC, closed without merging