solution was added
mate-academy/react_keyboard pull request #241
Opened 2022-10-13 16:48 UTC by Maksym845

- [DEMO LINK](https://Maksym845.github.io/react_keyboard/)

2022-10-15 06:25 UTC, Yeliseiev approved these changes

2022-10-15 06:25 UTC, Yeliseiev commented on src/App.tsx
> +  }
```suggestion
  componentDidMount() {
    document.addEventListener('keyup', this.handler);
  }
```

2022-10-15 06:25 UTC, Yeliseiev commented on src/App.tsx
> +  render(): ReactNode {
Why do you need 'ReactNode' here?

2022-10-17 12:59 UTC, OleksiiBlezniuk requested changes

2022-10-17 12:59 UTC, OleksiiBlezniuk commented on src/App.tsx
> +  };
or you could set empty string here

2022-10-17 12:59 UTC, OleksiiBlezniuk commented on src/App.tsx
> +      this.handler(event)));
just pass handler here, no need to create extra function

2022-10-17 12:59 UTC, OleksiiBlezniuk commented on src/App.tsx
> +      this.handler(event)));
same here

2022-10-17 12:59 UTC, OleksiiBlezniuk commented on src/App.tsx
> +          {this.state.pressedKey !== null
use destructuring assignment for state properties

2022-10-18 08:22 UTC, OleksiiBlezniuk approved these changes

2023-04-28 17:27 UTC, closed without merging