solution
mate-academy/react_keyboard pull request #652
Opened 2023-03-18 14:07 UTC by vadym4che

[DEMO LINK](https://vadym4che.github.io/react_keyboard/)

2023-03-21 12:34 UTC, sergii-nosachenko requested changes

2023-03-21 12:34 UTC, sergii-nosachenko commented on src/App.tsx
> +  state = {
Set state to be Readonly

2023-03-21 12:34 UTC, sergii-nosachenko commented on src/App.tsx
> +    const k = event.key;
What is `k`? Use destructuring.

2023-03-21 12:34 UTC, sergii-nosachenko commented on src/App.tsx
> +          {key !== null
```suggestion
          {pressedKey
```

2023-03-21 12:34 UTC, sergii-nosachenko commented on src/App.tsx
> +    const { pressedKey: key } = this.state;
You don't need to rename variable

2023-03-25 01:24 UTC, vadym4che commented on src/App.tsx
> +  state = {
fixed

2023-03-25 01:26 UTC, vadym4che commented on src/App.tsx
> +    const k = event.key;
fixed

2023-03-25 01:27 UTC, vadym4che commented on src/App.tsx
> +          {key !== null
fixed

2023-03-25 01:27 UTC, vadym4che commented on src/App.tsx
> +    const { pressedKey: key } = this.state;
fixed

2024-12-09 10:33 UTC, closed without merging