add task solution
mate-academy/react_keyboard pull request #802
Opened 2023-05-29 13:42 UTC by maksym-nemera

[DEMO LINK](https://maksym-nemera.github.io/react_keyboard/)

2023-05-31 15:36 UTC, dinaminahi requested changes
Good job 👍 
but let's fix few moments

2023-05-31 15:36 UTC, dinaminahi commented on src/App.tsx
> +    document.addEventListener('keyup', (event: KeyboardEvent) => {
let's create a separate function for event

2023-05-31 15:36 UTC, dinaminahi commented on src/App.tsx
> +    document.removeEventListener('keyup', this.componentDidMount);
and use it here instead of lifecycle method

2023-06-01 06:37 UTC, dinaminahi commented on src/App.tsx
> +  componentDidMount(): void {
No need of specifying return `void` type, typescript can handle this by itself

2023-06-05 09:22 UTC, silchyn approved these changes

2023-07-05 07:17 UTC, closed without merging