add solution
mate-academy/react_keyboard pull request #829
Opened 2023-06-08 14:38 UTC by serentinos

[DEMO LINK](https://serentinos.github.io/react_keyboard/)

2023-06-09 13:33 UTC, 33Orange requested changes
Almost done

A few moments to fix

2023-06-09 13:33 UTC, 33Orange commented on src/App.tsx
> +    key: '',
Use `null` instead empty string for initial empty value

2023-06-09 13:33 UTC, 33Orange commented on src/App.tsx
> +  keyboardHandler = (event: KeyboardEvent) => {
```suggestion
  handleKeyUp= (event: KeyboardEvent) => {
```

2023-06-12 08:52 UTC, naziamoff approved these changes
awesome 🔥

2023-08-14 11:53 UTC, closed without merging